### ISSUE TITLE
Server Crash on new member joining faction that has faction chat discord link

### ISSUE THREAD

**Issue by Blaylock1988** [Bishbash777/SEDB-RELOADED#26]
Crash upon an SEDB/SteamID linked player joining an existing faction that is has its chat linked to an SEDB faction.

```18:13:26.0880 [INFO]   SEDiscordBridge.FactionManager: Player 76561197983275102 joined to DU2.test faction 2
18:13:26.4734 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Entities.DiscordGuild.GrantRoleAsync(DiscordMember member, DiscordRole role, String reason)
   at SEDiscordBridge.DiscordBridge.<RaiseMemberJoined>d__44.MoveNext() in D:\prog\csharp\se\SE_mods\SEDB\SEDiscordBridge\DiscordBridge.cs:line 461
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Entities.DiscordGuild.GrantRoleAsync(DiscordMember member, DiscordRole role, String reason)
   at SEDiscordBridge.DiscordBridge.<RaiseMemberJoined>d__44.MoveNext() in D:\prog\csharp\se\SE_mods\SEDB\SEDiscordBridge\DiscordBridge.cs:line 461
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
18:13:26.4734 [INFO]   Initializer: Generating minidump at C:\SeServers\SE_7_5_Events\Instance\Minidump.dmp
18:13:26.4734 [ERROR]  Initializer: Keen broke the minidump, sorry.```

**Comment by Blaylock1988** [comment]
I apologize, these issues should have been for LTP's fork. We had mixed up plugin zip files on the server.
