### ISSUE TITLE
Crash on player connect

### ISSUE THREAD

**Issue by N1Ran** [Bishbash777/SEDB-RELOADED#32]
Version: 2.0.2.8

```xml
13:22:45.3699 [INFO]   SEDiscordBridge.SEDiscordBridgePlugin: DiscordID for That Guy found! Retrieving role data and injecting into essentials...
13:22:45.3699 [INFO]   Essentials.PlayerAccountModule: DiscordID for 76561198072860159 received from SEDB!... Inserting into player account (728665617833525362)
13:22:45.4810 [FATAL]  Initializer: DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<ListGuildMembersAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at DSharpPlus.Entities.DiscordGuild.<GetAllMembersAsync>d__136.MoveNext()
DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.Net.DiscordApiClient.<ListGuildMembersAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at DSharpPlus.Entities.DiscordGuild.<GetAllMembersAsync>d__136.MoveNext()
   ```

**Comment by Bishbash777** [comment]
Make sure bot has administative permissions in your server :)
