### ISSUE TITLE
Servers hosted on linux using winetricks are incompatible with SEDB

### ISSUE THREAD

**Issue by Michael-Codelabs** [Bishbash777/SEDB-RELOADED#62]
[2024-08-16 01:47:56 +00:00] [101 /Startup     ] [Info ] DSharpPlus, version 4.3
.0-nightly-01134
wine: Call from 00006FFFFF463DF7 to unimplemented function websocket.dll.WebSocketCreateClientHandle, aborting
[2024-08-16 01:47:57 +00:00] [102 /ConnectionFa] [Error] Connection attempt fail
ed, retrying in 7s
System.TypeInitializationException: The type initializer for 'System.Net.WebSock
ets.WebSocketProtocolComponent' threw an exception. ---> System.Runtime.InteropS
ervices.SEHException: External component has thrown an exception.
   at System.Net.WebSockets.WebSocketProtocolComponent.WebSocketCreateClientHand
le_Raw(Property[] properties, UInt32 propertyCount, SafeWebSocketHandle& webSock
etHandle)
   at System.Net.WebSockets.WebSocketProtocolComponent.GetSupportedVersion()
   at System.Net.WebSockets.WebSocketProtocolComponent..cctor()
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at DSharpPlus.Net.WebSocket.WebSocketClient.<ConnectAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwai
ter.GetResult()
   at DSharpPlus.DiscordClient.<InternalConnectAsync>d__483.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwai
ter.GetResult()
   at DSharpPlus.DiscordClient.<ConnectAsync>d__46.MoveNext()

**Comment by artificialai223** [comment]
+1
